### ISSUE TITLE
docs: Missing "Create Your Own Images docs

### ISSUE THREAD

**Issue by hillct** [leaningtech/labs#164]
When navigating from https://cheerpx.io/docs/getting-started the link to "Create your own images" yields a 404

For bug completeness, lets say the expected behavior :) is to see documentation on filesystem device creation

**Comment by alexp-sssup** [comment]
Thanks for reporting this, in the mean time the correct link is: https://cheerpx.io/docs/guides/custom-images

**Comment by alexp-sssup** [comment]
@AtibQur Please fix this issue when you have an opportunity

**Comment by AtibQur** [comment]
This issue has been fixed. Thank you for reporting it @hillct
